services:
  app:
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    networks:
      - general
  mysql:
    image: mysql:8.2.0
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=magazordapi
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=maga
      - MYSQL_PASSWORD=zord
    networks:
      - general
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - general
networks:
  general:
    driver: "bridge"
