services:
  mysql:
    build:
      context: .
      target: mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - general

  app:
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - general

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - general

networks:
  general:
    driver: "bridge"
